DECLARE
  TYPE PRUEBA IS VARRAY(4) OF MG_CLIENTES.NOMBRES%TYPE;
  V_CLIENTES     PRUEBA;
  N              NUMBER:=1;
BEGIN
  V_CLIENTES := PRUEBA ('Manuel', 'Raul', 'Santiago', 'Tolomeo');
  DBMS_OUTPUT.PUT_LINE('Total  = '||V_CLIENTES.COUNT());
  DBMS_OUTPUT.PUT_LINE('Maximo = '||V_CLIENTES.LIMIT);
END;
/