DECLARE
  CURSOR C_CONSTRAINTS IS
    SELECT CONSTRAINT_NAME, TABLE_NAME
      FROM USER_CONSTRAINTS
     WHERE CONSTRAINT_TYPE IN ('P','R','U')
  ORDER BY LAST_CHANGE ;

  Lv_Dinamico     VARCHAR2(4000);
  Lv_Accion       VARCHAR2(30):='&Accion';
BEGIN
  FOR CONS IN C_CONSTRAINTS
  LOOP
    Lv_Dinamico := 'ALTER TABLE '||CONS.TABLE_NAME||' '||Lv_Accion||' CONSTRAINT '||CONS.CONSTRAINT_NAME;
    EXECUTE IMMEDIATE LV_DINAMICO;
  END LOOP;
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END; 