DECLARE
  GN_VISITA_ID          ME_VISITA_CLIENTES.VISITA_ID                       %TYPE;
  GN_CODIGO_EMPRESA     ME_VISITA_CLIENTES.CODIGO_EMPRESA                  %TYPE;
  GN_CODIGO_CLIENTE     ME_VISITA_CLIENTES.CODIGO_PERSONA                  %TYPE;
  GN_COD_ENCUESTAS      ME_PREGUNTAS_ENCUESTAS.CODIGO_ENCUESTA             %TYPE;
  GN_TIP_ENCUESTAS      ME_PREGUNTAS_ENCUESTAS.CODIGO_TIPO_ENCUESTA        %TYPE;
  GR_REGISTROS          ME_K_ALTERNATIVAS_ENCUESTA.T_ALTERNATIVAS;
  LN_CODIGO_PREGUNTA    ME_PREGUNTAS_ENCUESTAS.CODIGO_PREGUNTA             %TYPE;
  LV_TEXTO_PREGUNTA     ME_PREGUNTAS_ENCUESTAS.TEXTO_PREGUNTA              %TYPE;
  LV_ES_PREG_CERRADA    ME_PREGUNTAS_ENCUESTAS.ES_PREGUNTA_CERRADA         %TYPE;
  LN_CODIGO_ENCUESTA    ME_PREGUNTAS_ENCUESTAS.CODIGO_ENCUESTA             %TYPE;
  LN_COD_TIP_ENC        ME_PREGUNTAS_ENCUESTAS.CODIGO_TIPO_ENCUESTA        %TYPE;
  LN_COD_PREG_APLICA    ME_PREGUNTA_APLICA_ENCUESTA.CODIGO_PREGUNTA_APLICA %TYPE;
BEGIN
  GN_VISITA_ID      := 1;
  GN_CODIGO_EMPRESA := 1;
  GN_CODIGO_CLIENTE := 40745;
  GN_COD_ENCUESTAS  := 2;
  GN_TIP_ENCUESTAS  := 1;

  ME_K_ALTERNATIVAS_ENCUESTA.ME_P_CONSULTA_ALTERNATIVAS(
    GN_VISITA_ID      => GN_VISITA_ID,
    GN_CODIGO_EMPRESA => GN_CODIGO_EMPRESA,
    GN_CODIGO_CLIENTE => GN_CODIGO_CLIENTE,
    GN_COD_ENCUESTAS  => GN_COD_ENCUESTAS,
    GN_TIP_ENCUESTAS  => GN_TIP_ENCUESTAS,
    GR_REGISTROS      => GR_REGISTROS
  );

  LOOP
    FETCH GR_REGISTROS INTO LN_CODIGO_PREGUNTA, LV_TEXTO_PREGUNTA, LV_ES_PREG_CERRADA, LN_COD_TIP_ENC,
                            LN_CODIGO_ENCUESTA, LN_COD_PREG_APLICA;
    EXIT WHEN GR_REGISTROS%NOTFOUND;

    DBMS_OUTPUT.PUT_LINE(LN_CODIGO_PREGUNTA||' - '||
                         LV_TEXTO_PREGUNTA ||' - '||
                         LV_ES_PREG_CERRADA||' - '||
                         LN_CODIGO_ENCUESTA||' - '||
                         LN_COD_TIP_ENC    ||' - '||
                         LN_COD_PREG_APLICA);
  END LOOP;
END;